### ISSUE TITLE
智能设站和自动生成站名现在不能工作

### ISSUE THREAD

**Issue by cardamage19248** [BusLineDesigner/buslinedesigner.github.io#2]
现在无法自动生成站名，总是显示（新站点 #20A335C2）而不是（钟楼东）这样的现实站名
同时智能设站也失效了，只能两点连接直线
（至少前几天还是好的今天就不行了）

**Comment by BobLiu0518** [comment]
抱歉一直没看Issue OvO
高德地图12月中旬大幅降低了个人开发者账号的免费api调用限额…所以key调用量现在天天超限
不过最近添加了自定义key的功能，可以去B站/微信公众号看看细节
