### ISSUE TITLE
添加与railmapgen/railmapgen.github.io的友情链接

### ISSUE THREAD

**Issue by thekingofcity** [BusLineDesigner/buslinedesigner.github.io#4]
嗨，BusLineDesigner是一个非常优秀的公共交通项目。在各个平台上都能看到生成自BusLineDesigner的内容，取得的成绩有目共睹。

作为另一公共交通项目的贡献者，诚邀项目贡献者在项目首页上交换两个项目的地址，互相宣传。

地铁线路图工具包是一个可以在网页上自由设计各种城市地铁线路图及门板图的开源前端应用程序。更多的信息欢迎访问 https://railmapgen.github.io/

如项目贡献者感兴趣，欢迎留下邮箱或其他联系方式进一步沟通。
期待与BusLineDesigner的合作 :)

**Comment by thekingofcity** [comment]
也感谢您的肯定与支持 :)

2.1版本中以页面底部文字链接形式展示完全没有问题，3.0新版本这样也很好看。不过如果可以的话希望3.0钟仅有一个链接，即 _地铁线路图工具包_，图片可以使用现有地铁线路图生成器rmg的。如果您考虑多语言支持的话英文为 _Rail Map Toolkit_。

地铁线路图工具包有预留友情链接位置，不过目前尚未考虑到图标支持。简单预览如下，如果您有中文标题亦或是图标的需求，欢迎讨论，我们将尽量满足您的意见。

![image](https://github.com/BusLineDesigner/buslinedesigner.github.io/assets/3353040/431b497f-3888-453e-a01c-a0e331da12c1)

**Comment by BobLiu0518** [comment]
谢谢，这样就好😊

我会尽快在当前版本中添加*地铁线路图工具包*的链接，不过请问在 3.0 中的，工具包的描述栏（即标题下方的小字）如何填写，还请告知☺️

**Comment by thekingofcity** [comment]
工具包的描述栏使用 _设计你的地铁线路图_ 即可，谢谢 :)

另外链接麻烦添加一个Google Analytics的额外参数，帮助我们更好地了解来自BusLineDesigner的用户：https://railmapgen.github.io/?utm_source=BusLineDesigner （您可以自定义utm_source的值，只要包含bld这样的内容即可，方便我们区分）

如果您也需要在地铁线路图工具包的链接中添加类似参数，也请回复所需的链接。目前使用的是：https://buslinedesigner.bobliu.tech/

**Comment by BobLiu0518** [comment]
已经在当前版本中添加链接：c739d5f

附 3.0 版本效果图：
![screenshot](https://github.com/BusLineDesigner/buslinedesigner.github.io/assets/24805093/e2359780-29a9-4da3-9c3a-d573c3ead70f)

Bus Line Designer 目前没有使用统计工具，暂时不需要添加此类参数，谢谢！

再次感谢您对 Bus Line Designer 的肯定和支持！

**Comment by thekingofcity** [comment]
嗨，地铁线路图工具包友情链接已添加并上线正式环境，参见：railmapgen/railmapgen.github.io#88

感谢您的全力合作与支持，如有任何未尽事宜欢迎重开议题继续讨论 :)
